<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="0" ignored="0" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="105" started-at="2019-12-23T11:44:31Z" finished-at="2019-12-23T11:44:31Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="105" started-at="2019-12-23T11:44:31Z" finished-at="2019-12-23T11:44:31Z">
      <class name="com.project.CBITMavenProject.TestDependency">
        <test-method status="PASS" signature="orange()[pri:1, instance:com.project.CBITMavenProject.TestDependency@c038203]" name="orange" duration-ms="23" started-at="2019-12-23T17:14:31Z" finished-at="2019-12-23T17:14:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orange -->
        <test-method status="PASS" signature="white()[pri:2, instance:com.project.CBITMavenProject.TestDependency@c038203]" name="white" duration-ms="3" started-at="2019-12-23T17:14:31Z" depends-on-methods="com.project.CBITMavenProject.TestDependency.orange" finished-at="2019-12-23T17:14:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- white -->
        <test-method status="SKIP" signature="blue()[pri:3, instance:com.project.CBITMavenProject.TestDependency@c038203]" name="blue" duration-ms="3" started-at="2019-12-23T17:14:31Z" depends-on-methods="com.project.CBITMavenProject.TestDependency.white" finished-at="2019-12-23T17:14:31Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[blue test skipped]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: blue test skippedat com.project.CBITMavenProject.TestDependency.blue(TestDependency.java:26)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- blue -->
        <test-method status="SKIP" signature="green()[pri:4, instance:com.project.CBITMavenProject.TestDependency@c038203]" name="green" duration-ms="0" started-at="2019-12-23T17:14:31Z" depends-on-methods="com.project.CBITMavenProject.TestDependency.blue" finished-at="2019-12-23T17:14:31Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDependency.green()[pri:4, instance:com.project.CBITMavenProject.TestDependency@c038203] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDependency.green()[pri:4, instance:com.project.CBITMavenProject.TestDependency@c038203] depends on not successfully finished methodsat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:878)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- green -->
      </class> <!-- com.project.CBITMavenProject.TestDependency -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
